### ISSUE TITLE
How to do Object detection on target domain(ex: Clipart) that don't have annotation.xml label

### ISSUE THREAD

**Issue by nileshmis** [harsh-99/SCL#16]
hey harsh-99,
I want to do object detection on clipart(target domain) dataset and i am training my model using pascal dataset as (source domain) and clipart dataset as (target domain) both have annotation.xml, but what if clipart dataset(target domain) don't have annotation.xml, how to do object detection on clipart sample that don't have annotation.xml, i tried to remove/comment annotation.xml code but i am getting error, how to solve or approach to this issue,Thanks in advance.

**Comment by harsh-99** [comment]
Hi, 
Just to make sure one thing, that when you are doing adaptation you do no need the annotation of target domain. The annotation of target domain is only required during validation or testing when you have to evaluate model performance. I am not sure about the code which you are using, but I could certainly tell this thing that during training you do not require annotation for target domain. There might be some other issue due to which you are getting error in code.

**Comment by nileshmis** [comment]
Thanks man understood, actually i was confused with respect to dataset, i realised now dummy data can be used for annotation.
